pub mod api;
pub mod auth;
pub mod bridge;
pub mod cli;
pub mod compile;
pub mod doctor;
pub(crate) mod file_util;
pub mod ignore;
pub mod jj;
pub mod operations;
pub mod output;
pub(crate) mod platform;
pub mod project;
pub mod review;
pub mod skill;
pub mod socket;
pub mod store;
pub mod sync;

pub const DEFAULT_BASE_URL: &str = "https://www.overleaf.com";
