name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test:
    name: Test · ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux AMD64
            os: ubuntu-22.04
          - name: Linux ARM64
            os: ubuntu-24.04-arm
          - name: macOS Apple Silicon
            os: macos-14
          - name: macOS Intel
            os: macos-15-intel
          - name: Windows AMD64
            os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: clippy
      - run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - run: cargo test --all-targets --locked
